name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: 
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Dependencies
      run: npm ci
    - name: Run Build
      run: npm run build
    - name: Run Unit Tests
      run: npm run test

