# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: 
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm ci
    - name: Run Build
      run: npm run build
    - name: Run Unit Tests
      run: npm run test

